language: python
python:
  - "3.6"

addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database huxy_tours;' -U postgres
services:
  - redis-server
  - postgresql

install:
  - pip3 install -r requirements.txt
  - pip install pytest pytest-cov

script:
  - nosetests --with-coverage

after_success:
  bash <(curl -s https://codecov.io/bash)