"""newMigration postgres

Revision ID: 19d9f4de92c9
Revises: 
Create Date: 2020-07-13 00:57:29.945530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d9f4de92c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tourpackage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_type', sa.String(length=50), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availabledates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_available', sa.Date(), nullable=True),
    sa.Column('tour_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tour_date'], ['tourpackage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('tour', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tour'], ['tourpackage.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_Packages', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('tour_type', sa.String(length=50), nullable=True),
    sa.Column('danger_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tour_Packages'], ['tourpackage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destinations')
    op.drop_table('booking')
    op.drop_table('availabledates')
    op.drop_table('weather_forecasts')
    op.drop_table('users')
    op.drop_table('tourpackage')
    # ### end Alembic commands ###
