"""Add Availaible dates

Revision ID: b0af3832a8b7
Revises: 
Create Date: 2020-07-07 22:49:51.694670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0af3832a8b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tourpackage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('available_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_', sa.String(length=50), nullable=True),
    sa.Column('tour_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tour_date'], ['tourpackage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_Packages', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('danger_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tour_Packages'], ['tourpackage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destinations')
    op.drop_table('available_dates')
    op.drop_table('tourpackage')
    # ### end Alembic commands ###
