"""Add user and bookings

Revision ID: cbb8921272c8
Revises: 
Create Date: 2020-07-11 23:29:24.442100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb8921272c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tourpackage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('availabledates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_available', sa.String(length=50), nullable=True),
    sa.Column('tour_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tour_date'], ['tourpackage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('tour', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tour'], ['tourpackage.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_Packages', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('tour_type', sa.String(length=50), nullable=True),
    sa.Column('danger_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tour_Packages'], ['tourpackage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destinations')
    op.drop_table('booking')
    op.drop_table('availabledates')
    op.drop_table('users')
    op.drop_table('tourpackage')
    # ### end Alembic commands ###
