"""Update weather model

Revision ID: fda8915ef62b
Revises: 8ca46bd21362
Create Date: 2020-07-12 22:03:07.348955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda8915ef62b'
down_revision = '8ca46bd21362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_forecasts', sa.Column('latitude', sa.String(length=20), nullable=True))
    op.add_column('weather_forecasts', sa.Column('longitude', sa.String(length=20), nullable=True))
    op.add_column('weather_forecasts', sa.Column('name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_forecasts', 'name')
    op.drop_column('weather_forecasts', 'longitude')
    op.drop_column('weather_forecasts', 'latitude')
    # ### end Alembic commands ###
